EventPlanner/EventPlanner/Models/Categorie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EventPlanner.Models
{
    public class Categorie
    {
        [Key]
        public int CategorieId { get; set; }

        [Required]
        [Display(Name ="Categorie naam")]
        public string CategorieName { get; set; }

        [Required]
        [Display(Name = "Beschrijving")]
        public string Info { get; set; }


    }
}

EventPlanner/EventPlanner/Controllers/CoachController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using EventPlanner.Data;
using EventPlanner.Models;
using EventPlanner.ViewModels;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;

namespace EventPlanner.Controllers
{
    public class CoachController : Controller
    {
        private EventPlannerContext db;
        private IWebHostEnvironment _environment;
        private readonly long _fileSizeLimit;
        private string[] permittedExtensions = { ".png", ".jpg", ".jpeg" };

        public CoachController(EventPlannerContext db, IWebHostEnvironment environment, IConfiguration config)
        {
            this.db = db;
            this._environment = environment;
            _fileSizeLimit = config.GetValue<long>("FileSizeLimit");
        }

        [Authorize(Roles = "Admin, Rockstar")]
        public IActionResult Coaches(int pageSelection)
        {
            if (pageSelection == 0)
            {
                pageSelection = 1;
            }
            decimal pageSize = 3;
            decimal eventCount;
            decimal page = Convert.ToDecimal(pageSelection);

            List<Coach> coaches = db.Coaches.Where(x => x.CoachId > 0).Skip((int)((page - 1) * pageSize)).Take((int)pageSize).ToList();
            eventCount = db.Coaches.Where(x => x.CoachId > 0).Count();
            int pages = Convert.ToInt32(Math.Ceiling(eventCount / pageSize));

            CoachViewModel model = new CoachViewModel()
            {
                Coaches = coaches,
                Pages = pages,
                PageNumber = pageSelection
            };
            return View(model);

        }

        [Authorize(Roles = "Admin, Rockstar")]
        public IActionResult CoachPage(int coachID)
        {
            List<Coach> coaches = db.Coaches.Where(x => x.CoachId == coachID).ToList();
            if (coaches.Count > 0)
            {
                Coach coach = coaches[0];
                CoachViewModel model = new CoachViewModel()
                {
                    CoachId = coach.CoachId,
                    Name = coach.Name,
                    Info = coach.Info,
                    Email = coach.Email,
                    ImageSrc = coach.ImageSrc
                };
                return View(model);
            }
            else
            {
                return View("PageNotFoundError");
            }
        }

        [Authorize(Roles = "Admin")]
        public IActionResult CoachAdd()
        {
            return View(new CoachAddViewModel());
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> CoachAdd(CoachAddViewModel model)
        {
            Coach realmodel = new Coach();

            if (ModelState.IsValid)
            {
                var uploads = Path.Combine(_environment.WebRootPath, "Images/Coaches");
                if (model.files != null)
                {
                    foreach (var file in model.files)
                    {
                        var ext = Path.GetExtension(file.FileName).ToLowerInvariant();
                        if (file.Length > 0 && file.Length < _fileSizeLimit && permittedExtensions.Contains(ext))
                        {
                            realmodel.ImageSrc = file.FileName;
                            using (var fileStream = new FileStream(Path.Combine(uploads, file.FileName), FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                            }
                        }
                        else
                        {
                            return View("CoachAddFail");
                        }
                    }
                }



                realmodel.CoachId = model.CoachId;
                realmodel.Name = model.Name;
                realmodel.Info = model.Info;
                realmodel.Email = model.Email;

                db.Coaches.Add(realmodel);
                db.SaveChanges();
                return View("CoachAddSucces");
            }
            else
                return View("CoachAddFail");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult CoachDeletePage(int coachID)
        {
            List<Coach> coaches = db.Coaches.Where(x => x.CoachId == coachID).ToList();
            Coach coach = coaches[0];
            CoachDeleteViewModel model = new CoachDeleteViewModel()
            {
                CoachId = coach.CoachId,
                Name = coach.Name
            };
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult DeleteCoach(int coachID)
        {
            List<Coach> coaches = db.Coaches.Where(x => x.CoachId == coachID).ToList();
            db.Coaches.Remove(coaches[0]);
            db.SaveChanges();
            return RedirectToAction("CoachDeleteComplete");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult CoachDeleteComplete()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult ChangeCoachPage(int coachID)
        {
            List<Coach> coaches = db.Coaches.Where(x => x.CoachId == coachID).ToList();
            Coach model = coaches[0];
            CoachAddViewModel realmodel = new CoachAddViewModel();

            realmodel.CoachId = model.CoachId;
            realmodel.Name = model.Name;
            realmodel.Info = model.Info;
            realmodel.Email = model.Email;
            realmodel.ImageSrc = model.ImageSrc;


            return View(realmodel);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> ChangeCoachPage(CoachAddViewModel model)
        {
            Coach realmodel = new Coach();
            if (ModelState.IsValid)
            {
                var uploads = Path.Combine(_environment.WebRootPath, "Images/Coaches");
                if (model.files != null)
                {
                    foreach (var file in model.files)
                    {
                        var ext = Path.GetExtension(file.FileName).ToLowerInvariant();
                        if (file.Length > 0 && file.Length < _fileSizeLimit && permittedExtensions.Contains(ext))
                        {
                            realmodel.ImageSrc = file.FileName;
                            using (var fileStream = new FileStream(Path.Combine(uploads, file.FileName), FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                            }
                        }
                        else
                        {
                            return View("ChangeCoachFail");
                        }
                    }
                }


                realmodel.CoachId = model.CoachId;
                realmodel.Name = model.Name;
                realmodel.Info = model.Info;
                realmodel.Email = model.Email;
                if (model.files == null)
                {
                    realmodel.ImageSrc = model.ImageSrc;
                }
                realmodel.Email = model.Email;


                List<Coach> coaches = db.Coaches.Where(x => x.CoachId == model.CoachId).ToList();
                Coach oldCoach = coaches[0];
                db.Entry(oldCoach).CurrentValues.SetValues(realmodel);
                db.SaveChanges();
                return RedirectToAction("AdminCoachPage", "Admin",new { realmodel.CoachId });
            }
            else
            {
                return View("ChangeCoachFail");
            }
        }
    }
}

EventPlanner/EventPlanner/Views/Shared/_AccessDenied.cshtml
<div id="CreateSuccess">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <h1 class="text-center">Toegang geweigerd.</h1>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <hr />
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <div class="row justify-content-center">
                    <a asp-area="" asp-controller="Account" asp-action="Login" class="btn btn-continue" style="margin: 0 auto;">Login met juiste account</a>
                </div>
            </div>
        </div>
    </div>
</div>

EventPlanner/EventPlanner/Views/Shared/_Categories.cshtml
@model CategoriesViewModel
@{

}

<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Categorieën
    </button>

    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        @foreach (var item in Model.Categories)
        {
            <a class="list-group-item">@Html.ActionLink(item.CategorieName, "CategoryPage", new { CategoryId = item.CategorieId })</a>
        }
        <div class="dropdown-divider" href="#"></div>
        <a class="dropdown-item" href="#">Alle categorieën</a>
    </div>
</div>

EventPlanner/EventPlanner/Views/Shared/_EventTemplate.cshtml
@model Event
<div class="container EventsBorder">
    <div class="row">
        <div class="col"><h4><a href='@string.Format("/Event/EventPage?eventID={0}", Model.EventId)'>@Model.EventName</a></h4><br /></div>
    </div>

    <div class="row">
        <div class="col"><h6>@Model.Date</h6> </div>
    </div>

    <div class="row">
        <div class="col"><h7>@Model.Location</h7><br /><br /></div>
    </div>

    <div class="row">
        <div class="col-3"><img class="rounded" style="max-width: 66%" src="~/Images/@Model.ImageSrc" /></div>
        <div class="col-9"><h8>@Model.Description</h8></div>
    </div>
</div>
<br />

EventPlanner/EventPlanner/Views/Shared/_EventTemplatePartial.cshtml
@model Event
<hr />
<br />
<div class="rounded container">
    <div class="row">
        @if (Model.Date > DateTime.Now)
        {
            <div class="col-10"><h4><a href='@string.Format("/Event/EventPage?eventID={0}", Model.EventId)'>@Model.EventName</a></h4><br /></div>
            <div class="col-2"><h6> @(Model.TotalVisitors) Vrije plaatsen</h6> </div>
        }
        else
        {
            <div class="col-12"><h4><a href='@string.Format("/Event/EventArchived?eventID={0}", Model.EventId)'>@Model.EventName</a></h4><br /></div>
        }
    </div>

    <div class="row">
        <div class="col-12"><h6>@Model.Date.ToString("g")</h6> </div>
    </div>

    <div class="row">
        <div class="col-sm-12"><h7>@Model.Location</h7><br /><br /></div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-3"><img class="rounded" style="max-width: 66%" src="~/Images/Events/@Model.ImageSrc" alt="@Model.ImageSrc.ToString()"/></div>
        <div class="col-sm-9 col-md-9"><h8>@Model.Description</h8></div>
    </div>
</div>
<br />

EventPlanner/EventPlanner/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/nl_NL/sdk.js#xfbml=1&version=v6.0"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <link href="~/css/site.css" rel="stylesheet" />
    <title>@ViewData["Title"] - EventPlanner</title>
</head>
<body>
    <main>
        <div class="container">
            <br />
            <nav class="navbar navbar-light bg-lignt navbar-expand-sm" style="padding: 1px; ">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/Logo/Logo.png" alt="Logo" style="width:60px;">
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse my-toggler" id="collapsibleNavbar">
                    <form class="form-inline" asp-action="Events" asp-controller="Event">
                        <input class="form-control mr-sm-" type="text" placeholder="Zoek een evenement" name="id" style="width:350px;">
                    </form>
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" asp-area="" asp-controller="Event" asp-action="Events" id="navbardrop" data-toggle="dropdown" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                               onMouseOut="this.style.color='#000'"> Evenementen </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Event" asp-action="Events"> Alle Evenementen </a>
                                <a class="dropdown-item" asp-controller="Event" asp-action="Categories"> Categorieën </a>
                                <a class="dropdown-item" asp-controller="Event" asp-action="EventArchive"> Gearchiveerde Evenementen </a>
                            </div>
                        </li>
                    </ul>
                    @if (User.IsInRole("Rockstar") || User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" asp-area="" asp-controller="Event" asp-action="Events" id="navbardrop" data-toggle="dropdown" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                                   onMouseOut="this.style.color='#000'"> Interne Evenementen </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Event" asp-action="EventsForEmployees"> Alle Evenementen</a>
                                    <a class="dropdown-item" asp-controller="Event" asp-action="EventArchiveForEmployees"> Gearchiveerde Evenementen </a>
                                </div>
                            </li>
                        </ul>
                    }

                    @if (User.IsInRole("Rockstar") || User.IsInRole("Admin"))
                    {
                        <a class="nav-link" asp-area="" asp-controller="Coach" asp-action="Coaches" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                           onMouseOut="this.style.color='#000'"> Coaches </a>
                    }

                    @if (User.IsInRole("Admin"))
                    {
                        <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="AdminEventPage" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                           onMouseOut="this.style.color='#000'"> Admin Omgeving</a>
                    }

                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                                   onMouseOut="this.style.color='#000'"> @User.Identity.Name </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Account" asp-action="AccountPage"> Gebruikerpagina </a>
                                    <a class="dropdown-item" asp-controller="Account" asp-action="EventRegistered"> Aangemelde evenementen </a>
                                    <form method="post" asp-controller="Account" asp-action="Logout">
                                        <button class="dropdown-item"> Uitloggen </button>
                                    </form>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                                   onMouseOut="this.style.color='#000'"> Registreer </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                                   onMouseOut="this.style.color='#000'"> Login </a>
                            </li>
                        }
                    </ul>
                </div>
            </nav>
            <hr />
            <br>


            @RenderBody()

        </div>
    </main>
    <!-- TODO: remove unnecessary br -->
    <br />
    <br />
    <br />
    <br />
    <footer class="footer">
        <div class="container">
            <hr />
            <div class="row align-items-center">
                <div class="col-md-4">
                    <h5>Social Media</h5>
                    <ul class="list-inline">
                        <li class="list-inline-item">
                            <a href="https://www.youtube.com/channel/UCvJNUHHMT1aDyjEUlEBaiFQ">
                                <i class="fa fa-youtube"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.facebook.com/teamrockstarsit/">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.instagram.com/teamrockstarsit/?hl=nl">
                                <i class="fa fa-instagram"></i>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.linkedin.com/company/teamrockstars/">
                                <i class="fa fa-linkedin"></i>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <span class="copyright">Copyright © Rockstars IT 2020</span>
                </div>
                <div class="col-md-4">
                    <h5>Links</h5>
                    <ul class="list-inline quicklinks">
                        <li class="list-inline-item">
                            <a href="https://www.teamrockstars.nl/">Team Rockstars IT</a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.teamupit.nl/">Rockstars IT Evenement Planner</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

EventPlanner/EventPlanner/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/nl_NL/sdk.js#xfbml=1&version=v6.0"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    <link href="~/css/site.css" rel="stylesheet" />
    <title>@ViewData["Title"] - EventPlanner</title>
</head>
<body>
    <main>
        <div class="container">
            <br />
            <nav class="navbar navbar-light bg-lignt navbar-expand-sm" style="padding: 1px; ">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/Logo/Logo.png" alt="Logo" style="width:60px;">
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse my-toggler" id="collapsibleNavbar">
                    <t><b>Admin Omgeving</b></t>
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" asp-area="" asp-controller="Event" asp-action="Events" id="navbardrop" data-toggle="dropdown" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                               onMouseOut="this.style.color='#000'"> Evenementen </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="Admin" asp-action="AdminEventPage"> Alle Evenementen </a>
                                <a class="dropdown-item" asp-controller="Admin" asp-action="AdminArchivedEventPage"> Gearchiveerde Evenementen </a>
                                <a class="dropdown-item" asp-controller="Admin" asp-action="EventDeleted"> Verwijderde Evenementen </a>
                            </div>
                        </li>
                    </ul>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="AdminCoachPage" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                       onMouseOut="this.style.color='#000'"> Coaches </a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="AdminAccountPage" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                       onMouseOut="this.style.color='#000'"> Accounts </a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="AdminCategoryPage" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                       onMouseOut="this.style.color='#000'"> Categorieën </a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="ListRoles" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                       onMouseOut="this.style.color='#000'"> Rollen </a>
                    <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="AdminNewsletterPage" style="color:black" onMouseOver="this.stylegit .color='#7e8691'"
                       onMouseOut="this.style.color='#000'"> Nieuwsbrief </a>

                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <button class="dropdown-item"> Uitloggen </button>
                            </form>
                        </li>
                    </ul>
                </div>
            </nav>
            <hr />
            <br>

            @RenderBody()
        </div>
    </main>
</body>
</html>